version: '3.8'
services:
  api:
    build:
      context: ./
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
      PORT: 8080
      EXCHANGE_RATE_API_URL: https://api.exchangerate-api.com
